/* This file has been generated by go-specgen. */
#include <stdint.h>
#include <stdio.h>


typedef enum {
	Pedestrian = 0x1,
	AI = 0x2,
	Vehicle = 0x4,
	TramStation = 0x8,
	Special = 0x10
} EPointType;

typedef enum {
	Pedestrian = 1,
	AI = 2,
	TrainsAndSalinas_Forward = 4,
	TrainsAndSalinas_Reverse = 0x8400,
	Other = 0x1000
} ELinkType;


typedef struct tagHEADER {
	uint32_t Magic; /* Should be 0x1ABCEDF */
	uint32_t PointCount; /* Number of points */
} Header;

typedef struct tagVECTOR3 {
	float x;
	float y;
	float z;
} Vector3;

typedef struct tagPOINT {
	Vector3 Position;
	EPointType Type;
	uint16_t ID;
	uint8_t Unk[10]; /* @plain Unknown values */
	uint8_t EnterLinks;
	uint8_t ExitLinks;
} Point;

typedef struct tagLINK {
	uint16_t TargetPoint;
	ELinkType LinkType;
	float Unk;
} Link;

