/* This file has been generated by go-specgen. */
#include <stdint.h>
#include <stdio.h>


typedef struct tagSPAMEGGS {
	float A;
	float B;
} SpamEggs;

typedef struct tagFOO {
	int32_t Bar;
	SpamEggs* Eggs;
} Foo;

typedef struct tagFOOBAR {
	Foo A;
	int8_t B[32]; /* Model name */
} FooBar;

