/* This file has been generated by go-specgen. */
#include <stdint.h>
#include <stdio.h>


typedef enum {
	Standard = 1, // Standard mesh type
	SingleMesh = 4, // Mesh consisting of bones and skin data
	Morph,
	Sector // Holds objects
} ModelTypeEnum;


typedef struct tagHEADER {
	int8_t Magic[4]; /* @plain Has to be 'PACK' */
	int32_t DirectoryOffset; /* Offset to the directory */
	int32_t DirectoryLength; /* Directory length */
} Header;

typedef struct tagDIRECTORY {
	int8_t FileName[56]; /* @string Archived file name */
	int32_t FilePosition;
	int32_t FileLength;
} Directory;

typedef struct tagFACEGROUP {
	int32_t MaterialID; /* -1 for default */
	uint16_t FaceCount;
	int64_t* Faces; /* @plain */
} FaceGroup;

typedef struct tagMODEL {
	uint32_t ModelType; /* Model type */
	uint16_t FaceGroupCount; /* Number of face groups */
	FaceGroup* FaceGroups; /* model's face groups */
} Model;

